# Generated by Django 4.2 on 2023-04-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diecast_Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="diecast_brand_img/")),
            ],
        ),
    ]
