# Generated by Django 4.2 on 2023-04-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_diecast_delete_diecast_brand_delete_vehicle_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diecast",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="diecast",
            name="image",
        ),
        migrations.RemoveField(
            model_name="diecast",
            name="picture",
        ),
        migrations.AlterField(
            model_name="diecast",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
