# Generated by Django 4.2.1 on 2023-05-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
