# Generated by Django 4.2.1 on 2023-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_product_brand_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': 'ProductAttributes'},
        ),
        migrations.RenameField(
            model_name='diecast',
            old_name='price',
            new_name='buying_price',
        ),
        migrations.AddField(
            model_name='diecast',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
