# Generated by Django 4.2.1 on 2023-05-09 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_options_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Manufacturer must be greater than 2 characters'), django.core.validators.MaxLengthValidator(30, 'Manufacturer must be less than 30 characters')])),
            ],
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Manufacturer must be greater than 2 characters'), django.core.validators.MaxLengthValidator(30, 'Manufacturer must be less than 30 characters')])),
            ],
        ),
        migrations.AlterField(
            model_name='diecast',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manufacturer'),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scale'),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='vehicle_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle_brand'),
        ),
    ]
