# Generated by Django 4.2.1 on 2023-05-09 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_manufacturer_scale_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecast',
            name='manufacturer',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Manufacturer must be greater than 2 characters'), django.core.validators.MaxLengthValidator(30, 'Manufacturer must be less than 30 characters')]),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='scale',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='vehicle_brand',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, 'Brand must be greater than 2 characters'), django.core.validators.MaxLengthValidator(30, 'Brand must be less than 30 characters')]),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
        migrations.DeleteModel(
            name='Vehicle_Brand',
        ),
    ]
