# Generated by Django 4.2.1 on 2023-05-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_manufacturer_scale_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_Brand',
            new_name='VehicleBrand',
        ),
    ]
