# Generated by Django 4.2.1 on 2023-05-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_productattribute_product_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AddField(
            model_name='diecast',
            name='picture_content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
    ]
