# Generated by Django 4.2.1 on 2023-05-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_diecast_picture_diecast_picture_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diecast',
            name='picture_content_type',
        ),
    ]
