# Generated by Django 4.2.1 on 2023-05-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_diecast_picture_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
    ]
