# Generated by Django 4.2.1 on 2023-05-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_year_diecast_production_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diecast',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='diecast',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
