# Generated by Django 4.2.1 on 2023-05-10 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_diecast_content_type_alter_diecast_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='inventory',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
