# Generated by Django 4.2.1 on 2023-05-10 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_diecast_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecast',
            name='vehicle_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Vehicle must be greater than 2 characters'), django.core.validators.MaxLengthValidator(50, 'Vehicle must be less than 1 characters')]),
        ),
    ]
