# Generated by Django 4.2.1 on 2023-05-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_diecast_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diecast',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
