# Generated by Django 4.2.1 on 2023-05-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_diecast_featured_diecast_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer/'),
        ),
    ]
