# Generated by Django 4.2.1 on 2023-05-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_manufacturer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
    ]
