# Generated by Django 4.2.1 on 2023-05-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_manufacturer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='on_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclebrand',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
    ]
