# Generated by Django 4.2.1 on 2023-05-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_vehiclebrand_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='on_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
