# Generated by Django 4.2.1 on 2023-05-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_diecast_slug_alter_diecast_on_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="DON'T NEED TO FILL IN", max_length=255),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="DON'T NEED TO FILL IN", max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="DON'T NEED TO FILL IN", max_length=255),
        ),
    ]
