# Generated by Django 4.2.1 on 2023-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_picture_diecast_picture1_diecast_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='diecast',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='diecast',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='diecast',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
