# Generated by Django 4.2.1 on 2023-05-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_diecast_picture5_diecast_picture6_diecast_picture7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecast',
            name='picture1',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='picture2',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='picture3',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='diecast',
            name='picture4',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
