# Generated by Django 4.2.1 on 2023-05-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_diecast_picture1_alter_diecast_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecast',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
