# Generated by Django 4.2.1 on 2023-05-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_diecast_picture4'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
