# Generated by Django 4.2.1 on 2023-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_scale_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(null=True, upload_to='carousel/')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
    ]
