# Generated by Django 4.2.1 on 2023-05-14 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_profile_diecast_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecast',
            name='save_percent',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99)]),
        ),
    ]
