# Generated by Django 4.2.1 on 2023-05-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(default='About Us', max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
