# Generated by Django 4.2.1 on 2023-05-16 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_aboutus_name_alter_aboutus_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
