# Generated by Django 4.2.1 on 2023-07-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
